{% set name = "decore" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b5885efa421cafac4b35faea042b213e8b0156f38d5d761c8957891bc0bb8f9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - decore
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/shaypal5/decore
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A small pure-python package for utility decorators.'

  description: |
    A small pure-python package for utility decorators.
  dev_url: https://github.com/shaypal5/decore

extra:
  recipe-maintainers:
    - Silun
    - shaypal5
